[tool.poetry]
name = "cover-letter-llm"
version = "0.1.0"
description = ""
authors = ["Kavish Hukmani <khukmani@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
langchain = "0.3.26"
langchain-community = "0.3.27"
langchain-openai = "0.3.27"
html2text = "2025.4.15"
streamlit = "1.46.1"
pypdf = "5.7.0"
pyperclip = "1.9.0"
python-dotenv = "1.1.1"
playwright = "1.53.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
